export const wordsEn = [
      { id: 1,  en: 'Mother',       tj: 'Модар' },
  { id: 2,  en: 'Father',       tj: 'Падар' },
  { id: 3,  en: 'Son',          tj: 'Писар' },
  { id: 4,  en: 'Daughter',     tj: 'Духтар' },
  { id: 5,  en: 'Brother',      tj: 'Бародар' },
  { id: 6,  en: 'Sister',       tj: 'Хоҳар' },
  { id: 7,  en: 'Grandfather',  tj: 'Бобо' },
  { id: 8,  en: 'Grandmother',  tj: 'Биби' },
  { id: 9,  en: 'Husband',      tj: 'Шавҳар' },
  { id: 10, en: 'Wife',         tj: 'Зан' },

  { id: 11, en: 'Child',        tj: 'Кӯдак' },
  { id: 12, en: 'Parents',      tj: 'Волидон' },
  { id: 13, en: 'Sun',          tj: 'Офтоб' },
  { id: 14, en: 'Moon',         tj: 'Моҳ' },
  { id: 15, en: 'Star',         tj: 'Ситора' },
  { id: 16, en: 'Sky',          tj: 'Осмон' },
  { id: 17, en: 'Earth',        tj: 'Замин' },
  { id: 18, en: 'Fire',         tj: 'Оташ' },
  { id: 19, en: 'Wind',         tj: 'Бод' },
  { id: 20, en: 'Water',        tj: 'Об' },

  { id: 21, en: 'Mountain',     tj: 'Кӯҳ' },
  { id: 22, en: 'River',        tj: 'Дарё' },
  { id: 23, en: 'Sea',          tj: 'Баҳр' },
  { id: 24, en: 'Lake',         tj: 'Кӯл' },
  { id: 25, en: 'Forest',       tj: 'Ҷангал' },
  { id: 26, en: 'Tree',         tj: 'Дарахт' },
  { id: 27, en: 'Flower',       tj: 'Гул' },
  { id: 28, en: 'Grass',        tj: 'Алаф' },
  { id: 29, en: 'Stone',        tj: 'Санг' },
  { id: 30, en: 'Snow',         tj: 'Барф' },

  { id: 31, en: 'Rain',         tj: 'Борон' },
  { id: 32, en: 'Cloud',        tj: 'Абр' },
  { id: 33, en: 'Bread',        tj: 'Нон' },
  { id: 34, en: 'Milk',         tj: 'Шир' },
  { id: 35, en: 'Meat',         tj: 'Гӯшт' },
  { id: 36, en: 'Apple',        tj: 'Себ' },
  { id: 37, en: 'Tea',          tj: 'Чой' },
  { id: 38, en: 'Salt',         tj: 'Намак' },
  { id: 39, en: 'Sugar',        tj: 'Шакар' },
  { id: 40, en: 'Soup',         tj: 'Шӯрбо' },

  { id: 41, en: 'Pilaf',        tj: 'Ош' },
  { id: 42, en: 'Rice',         tj: 'Биринҷ' },
  { id: 43, en: 'Oil',          tj: 'Равған' },
  { id: 44, en: 'Egg',          tj: 'Тухм' },
  { id: 45, en: 'Fish',         tj: 'Моҳӣ' },
  { id: 46, en: 'Chicken',      tj: 'Мурғ' },
  { id: 47, en: 'Grapes',       tj: 'Ангур' },
  { id: 48, en: 'Watermelon',   tj: 'Тарбуз' },
  { id: 49, en: 'Melon',        tj: 'Харбуза' },
  { id: 50, en: 'Pear',         tj: 'Нок' },
];